services:
  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_DB=$MYSQL_DB
        - MYSQL_USER=$MYSQL_US
        - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

  nginx:
    image: nginx:1.0
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_network
    restart: always

  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - "9001:9001"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/asoler/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/asoler/data/wordpress
      o: bind
      type: none

networks:
  inception_network:
    name: inception_network
