#!/bin/sh

wp config create --dbname=$MYSQL_DB --dbuser=$MYSQL_USER --dbpass=$MYSQL_PASSWORD --dbhost=$MYSQL_HOST --dbprefix=wp_

wp core install --url=$DOMAIN_NAME --title="$WP_TITLE" --admin_user=$WP_ADMIN_N --admin_password=$WP_ADMIN_P --admin_email=$WP_ADMIN_E

wp user create $WP_USER_N $WP_USER_E --user_pass=$WP_USER_P --role=subscriber

/usr/sbin/php-fpm83 -F
